[viewer]
    Title = "白皑Go语言博客"
    Description = "白皑Go语言博客"
    Logo = "/resource/images/OIP-C.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "#"
    Zhihu = "#"
    Avatar = "https://tse1-mm.cn.bing.net/th/id/R-C.7149311e3d8cfd47d77040a2a3ead529?rik=u7xEBl9JSQ0egw&riu=http%3a%2f%2fscimg.jianbihuadq.com%2ftouxiang%2f202003%2f20200326123252115.jpg&ehk=%2fc28AHbWAl%2bG0K7usiGE0gvImmL9Fh8y4aStQiRzyZI%3d&risl=&pid=ImgRaw&r=0&sres=1&sresct=1"
    UserName = "白皑"
    UserDesc = "长得非常帅的程序员"
[system]
    CdnURL = "自己的域名"
    QiniuAccessKey = "七牛云对象存储，自行申请"
    QiniuSecretKey = "替换自己的"
    Valine = true
    ValineAppid = "百度 valine"
    ValineAppkey = "替换自己的"
    ValineServerURL = "替换自己的"