[viewer]
    Title = "白皑Go语言博客"
    Description = "白皑Go语言博客"
    Logo = "/resource/images/OIP-C.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "#"
    Zhihu = "#"
    Avatar = "https://tse1-mm.cn.bing.net/th/id/R-C.7149311e3d8cfd47d77040a2a3ead529?rik=u7xEBl9JSQ0egw&riu=http%3a%2f%2fscimg.jianbihuadq.com%2ftouxiang%2f202003%2f20200326123252115.jpg&ehk=%2fc28AHbWAl%2bG0K7usiGE0gvImmL9Fh8y4aStQiRzyZI%3d&risl=&pid=ImgRaw&r=0&sres=1&sresct=1"
    UserName = "白皑"
    UserDesc = "长得非常帅的程序员"
[system]
    CdnURL = "https://r7jaesn7w.hn-bkt.clouddn.com"
    QiniuAccessKey = "BFqcUZldi0ZKl_H3ScXLf6w5qL75tLYQuNK5Uaz1"
    QiniuSecretKey = "dr5JI9m9SoMbdL28j4yVO7jF7x3g_JOmX8f9mhP6"
    Valine = true
    ValineAppid = "o9XXPb5cKeAy30XmMFXApu5w-gzGzoHsz"
    ValineAppkey = "D5Cito0RkfSrBMzdGiVHqX3Q"
    ValineServerURL = "https://o9xxpb5c.lc-cn-n1-shared.com"